### PR TITLE
fixed issues caused by renaming

### PR DESCRIPTION
**Pull request by hansmannj**
fixed some issues that were caused by renaming the app `project` to `stac_api`

### CODE REVIEW

**Comment by hansmannj** [comment]
Don't know why checks are failing. I needed to do these changes in order to be able to test with a local sqlite3 db. Without those changes, the admin pages cannot be created..

**Comment by ltshb** [comment]
I would suggest to first try to update the branch

**Comment by hansmannj** [comment]
Currently the tests are failing because a sqlite db is used for testing, which cannot work, as a postgres db is required in order to use ArrayFields..

**Comment by boecklic** [comment]
We should be careful with merge strategy in git: merging `develop` into a feature branch is often causing troubles. I propose we always **rebase** feature branches on `develop`, if upstream changes in `develop` are required in the feature branch. This keeps commit history in feature branches clean.

**Comment by boecklic** [comment]
and yeah, I'll try to fix remaining points in #22 asap so we can merge

**Comment by ltshb** [comment]
> We should be careful with merge strategy in git: merging `develop` into a feature branch is often causing troubles. I propose we always **rebase** feature branches on `develop`, if upstream changes in `develop` are required in the feature branch. This keeps commit history in feature branches clean.

I agree with this, currently we don't have any guideline regarding this and I started on (https://github.com/geoadmin/doc-guidelines/blob/feature_pr_workflow/PR_WORKFLOW.md) that we should all together discuss and agree.  Guideline are only useful if everyone stick to them :-)

**Review by boecklic — APPROVED** [review]
perfect, thnx!

**Comment by hansmannj** [comment]
Checks were still failing. I added the initial migrations. Perhaps that helps.
Test with a local db work now. Even admin pages are up and running with local server and local db :-)

**Comment by hansmannj** [comment]
finally :-)

**Pull request merged**
