### PR TITLE
Release v0.1.0

### PR DESCRIPTION
**Pull request by boecklic**
This is the first release (v0.1.0) that should be merged to master, tagged and deployed to `int`. 
Note that there's no proper version mgmt in place yet. It is done manually since we need a defined state on int now.

### CODE REVIEW

**Review by rebert — APPROVED** [review]
yeah

**Comment by boecklic** [comment]
That merge came a bit too quick, I wanted to wait for https://github.com/geoadmin/service-stac/pull/107 since it changes the spec again (PRs should normally be merged by the ones creating the PR...)

**Comment by hansmannj** [comment]
> That merge came a bit too quick, I wanted to wait for #107 since it changes the spec again (PRs should normally be merged by the ones creating the PR...)
> I'll manually make a hard reset and force push of `master` and reopen this PR

Just working on solving the conflicts in #107 
Hope it doesn't take too long..

**Comment by boecklic** [comment]
No hurry. I don't change current `master` and leave it as it is. Creating a release `v0.2.0` whenever your PR is done.

**Comment by rebert** [comment]
sorry

**Pull request merged**
