### PR TITLE
Added 'checker' endpoint, changed landing page to '/api/stac/v0.9'

### PR DESCRIPTION
**Pull request by hansmannj**
- Changed the landing page to be found under "api/stac/v0.9"
- added a simple "checker"-endpoint

### CODE REVIEW

**Review by ltshb — COMMENTED** [review]
Not sure about the checker endpoint should not it be `data.geo.admin.ch/checker` instead of `data.geo.admin.ch/api/stac/v0.9/checker` ? It has nothing to do with the STAC therefore I would no add it to the STAC path. @procrastinatio, @rebert, @boecklic, @ltkum what are your opinion on this ?

**Review by rebert — CHANGES_REQUESTED** [review]
I agree with @ltshb. Beside LGTM

**Comment by hansmannj** [comment]
makes sense, I've moved the checker endpoint to the root

**Comment by hansmannj** [comment]
something went wrong, my changes were overwritten. I'll push again, soon

**Review by ltshb — APPROVED** [review]
We might want in future to split the views but for the moment I think it is fine to have it in one file as it only have the checker.

**Review by rebert — APPROVED** [review]

**Pull request merged**
