### PR TITLE
added Jupyter notebook example for STAC API POST search endpoint

### PR DESCRIPTION
**Pull request by hansmannj**
Added a Jupyter notebook with an example for a simple POST /search usage

### CODE REVIEW

**Review by ltshb — COMMENTED** [review]
I'm not sure that this is the right place for such examples, @boecklic what do you think ?

**Review by boecklic — COMMENTED** [review]
We started this repo https://github.com/geoadmin/doc-jupyter-api with the intention at the time to compile a collection of jupyter notebooks that illustrate usage of our api.
Imho we should address this topic later this year in a broader context, i.e. API spec, docs, tutorials, how to, ...

**Comment by hansmannj** [comment]
> We started this repo https://github.com/geoadmin/doc-jupyter-api with the intention at the time to compile a collection of jupyter notebooks that illustrate usage of our api. Imho we should address this topic later this year in a broader context, i.e. API spec, docs, tutorials, how to, ...

Ah, great, was not aware of that repo!
So I'll move the notebook into that repo :+1:

**Review by rebert — COMMENTED** [review]
thx

**Pull request merged**
