### PR TITLE
BGDIINF_SB-1734 Remove md5 checksum support

### PR DESCRIPTION
**Pull request by ltclm**
This will remove the md5 support as described here: https://jira.swisstopo.ch/browse/BGDIINF_SB-1734

### CODE REVIEW

**Comment by ltclm** [comment]
@ltshb any idea why the codebuild pipeline is not working anymore?:

```
[Container] 2021/03/25 09:16:37 Phase complete: BUILD State: FAILED
--
1045 | [Container] 2021/03/25 09:16:37 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: docker build --build-arg GIT_HASH="${COMMIT_HASH}" --build-arg GIT_BRANCH="${GITHUB_BRANCH}" --build-arg AUTHOR="CI" --build-arg VERSION="${GIT_TAG}" -t "${DOCKER_IMG_TAG_DEV}" -t "${DOCKER_IMG_TAG_LATEST_DEV}" --target debug .
```

**Comment by ltshb** [comment]
@ltclm it failed because of the missing patch file `COPY failed: stat /var/lib/docker/tmp/docker-builder098276831/multihash.patch: no such file or directory` You need to remove it from the dockerfile as well.

**Review by ltshb — COMMENTED** [review]
Looks good, only the migration files that should not be needed, why have you migration file plus a  merge migrations ? I think if you are uptodate with the develop those migratons should not be needed? @boecklic  what do you mean ?

**Comment by ltclm** [comment]
yes i have removed the migrations

**Review by ltshb — APPROVED** [review]
:+1:

**Pull request merged**
