### PR TITLE
add random data loader sql script

### PR DESCRIPTION
**Pull request by ltclm**
this script will load random data into
* stac_api_collection
* stac_api_item

### CODE REVIEW

**Review by rebert — APPROVED** [review]

**Comment by ltshb** [comment]
@ltclm could revert the `Merge branch 'develop' into ...` commit and do a rebase to develop instead ? We try to keep the git history clean in service-stac based on the https://github.com/geoadmin/doc-guidelines/blob/master/GIT_FLOW.md. Thanks

**Comment by hansmannj** [comment]
Thanks for the useful script @ltclm. I guess this PR could be rebased and merged, or not?

**Comment by ltclm** [comment]
yes, theres nothing more to add from my side.

**Comment by ltclm** [comment]
@hansmannj  have rebased it

**Pull request merged**
