### PR TITLE
BGDIINF_SB-1670: Correct transactional examples in STAC spec

### PR DESCRIPTION
**Pull request by IsabelleBzr**
Corrected the transactional examples in STAC spec:
* removed read only properties
* changed id to small letters
* changed image type
* removed non supported properties

### CODE REVIEW

**Review by ltshb — APPROVED** [review]
:+1:

**Review by hansmannj — COMMENTED** [review]
:+1:

Just one little point:
We discussed this a while ago, and I can't remember exactly, what the final result was.
But this PR would be a chance to remove the `stac_extensions` from the response schema and also the response example here: https://data.geo.admin.ch/api/stac/static/spec/v0.9/apitransactional.html#operation/createCollection

Currently, `stac_extensions` is hard-coded to be empty. And as it is empty, it will not be part of the response. So we can simply delete it from the response schema and also the response example. If necessary in future, we can simply revert it and re-add it to the schema and the sample. What do you think about that @IsabelleBzr @ltshb ?

**Review by hansmannj — APPROVED** [review]

**Comment by ltshb** [comment]
@hansmannj  I would leave the `stac_extensions` in the SPEC as it is also present in the original radianearth SPEC. It is correct to have it the SPEC and having it in the service hard coded to an empty list. However related to this there is still some clean up in unittest to do see https://jira.swisstopo.ch/browse/BGDIINF_SB-1765

**Comment by hansmannj** [comment]
> @hansmannj I would leave the `stac_extensions` in the SPEC as it is also present in the original radianearth SPEC. It is correct to have it the SPEC and having it in the service hard coded to an empty list. However related to this there is still some clean up in unittest to do see https://jira.swisstopo.ch/browse/BGDIINF_SB-1765

Good point to check the radiant earth specs @ltshb. However I think it is more transparent to remove `stac_extensions` from the response schema and also the response example, as it currently will not appear in the response. So having it in the spec and not in the response would be strange.
`stac_extensions` are not a required field in the radiant earth specs. And we also have our own custom way to deal with other non-required fields (e.g. `keywords`). So I think it would be OK to remove it. What's your take @boecklic ?

**Comment by boecklic** [comment]
> `stac_extensions` are not a required field in the radiant earth specs. And we also have our own custom way to deal with other non-required fields (e.g. `keywords`). So I think it would be OK to remove it. What's your take @boecklic ?
If `stac_extensions` is not required (I haven't checked) and since it's not present in the payload I'd remove it from the spec.

**Pull request merged**
